/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as LetsGetRealRouteImport } from './routes/lets-get-real'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LetsGetRealSlugRouteImport } from './routes/lets-get-real.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const LetsGetRealRoute = LetsGetRealRouteImport.update({
  id: '/lets-get-real',
  path: '/lets-get-real',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LetsGetRealSlugRoute = LetsGetRealSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LetsGetRealRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/getting-started': typeof GettingStartedRoute
  '/lets-get-real': typeof LetsGetRealRouteWithChildren
  '/links': typeof LinksRoute
  '/lets-get-real/$slug': typeof LetsGetRealSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/getting-started': typeof GettingStartedRoute
  '/lets-get-real': typeof LetsGetRealRouteWithChildren
  '/links': typeof LinksRoute
  '/lets-get-real/$slug': typeof LetsGetRealSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/getting-started': typeof GettingStartedRoute
  '/lets-get-real': typeof LetsGetRealRouteWithChildren
  '/links': typeof LinksRoute
  '/lets-get-real/$slug': typeof LetsGetRealSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/getting-started'
    | '/lets-get-real'
    | '/links'
    | '/lets-get-real/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/getting-started'
    | '/lets-get-real'
    | '/links'
    | '/lets-get-real/$slug'
  id:
    | '__root__'
    | '/'
    | '/getting-started'
    | '/lets-get-real'
    | '/links'
    | '/lets-get-real/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GettingStartedRoute: typeof GettingStartedRoute
  LetsGetRealRoute: typeof LetsGetRealRouteWithChildren
  LinksRoute: typeof LinksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lets-get-real': {
      id: '/lets-get-real'
      path: '/lets-get-real'
      fullPath: '/lets-get-real'
      preLoaderRoute: typeof LetsGetRealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lets-get-real/$slug': {
      id: '/lets-get-real/$slug'
      path: '/$slug'
      fullPath: '/lets-get-real/$slug'
      preLoaderRoute: typeof LetsGetRealSlugRouteImport
      parentRoute: typeof LetsGetRealRoute
    }
  }
}

interface LetsGetRealRouteChildren {
  LetsGetRealSlugRoute: typeof LetsGetRealSlugRoute
}

const LetsGetRealRouteChildren: LetsGetRealRouteChildren = {
  LetsGetRealSlugRoute: LetsGetRealSlugRoute,
}

const LetsGetRealRouteWithChildren = LetsGetRealRoute._addFileChildren(
  LetsGetRealRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GettingStartedRoute: GettingStartedRoute,
  LetsGetRealRoute: LetsGetRealRouteWithChildren,
  LinksRoute: LinksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
